In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
import scipy.stats
%matplotlib inline
N=500
p=30
xi_patterns=np.zeros((p,N))
for i in range(p):
    for j in range(N):
        if random.uniform(0,1)<0.5:
            xi_patterns[i,j]=1
        else:
            xi_patterns[i,j]=-1
w=np.zeros((N,N))
#for i in range(N):
#    for j in range(N):
#        for myu in range(p):
#            w[i,j]=w[i,j]+1/N*xi_patterns[myu,i]*xi_patterns[myu,j]
for myu in range(p):
    w=w+1/N*np.dot(xi_patterns[myu].reshape(N,1),xi_patterns[myu].reshape(1,N))
print(w)

[[ 0.06   0.    -0.012 ...  0.     0.012  0.   ]
 [ 0.     0.06  -0.008 ... -0.004 -0.016  0.012]
 [-0.012 -0.008  0.06  ...  0.008  0.012 -0.016]
 ...
 [ 0.    -0.004  0.008 ...  0.06  -0.016 -0.012]
 [ 0.012 -0.016  0.012 ... -0.016  0.06   0.   ]
 [ 0.     0.012 -0.016 ... -0.012  0.     0.06 ]]


In [2]:
pr=np.zeros(p)
for sp in range(p):
    xi0=np.zeros(N)
    #sp=np.random.randint(0,p)
    for i in range(N):
        if random.uniform(0,1)<0.2:
            xi0[i]=-xi_patterns[sp,i]
        else:
            xi0[i]=xi_patterns[sp,i]
    xi=np.zeros(N)
    #for i in range(N):
    #    Sum=0
    #    for j in range(N):
    #        Sum=Sum+w[i,j]*xi0[j]
    #    if Sum>0:
    #        xi[i]=1
    #    elif Sum==0:
    #        xi[i]=0
    #    else:
    #        xi[i]=-1
    Sum=np.dot(w,xi0.reshape(N,1))
    for i in range(N):
        if Sum[i]>0:
            xi[i]=1
        elif Sum[i]==0:
            xi[i]=0
        else:
            xi[i]=-1
    pr[sp]=scipy.stats.pearsonr(xi_patterns[sp],xi)[0]
print(pr)

[1.         1.         1.         0.99600784 1.         0.9920287
 0.99600337 0.97219181 0.99202157 0.99198153 0.95606182 0.96803149
 0.9800712  0.99199949 1.         1.         1.         0.97997902
 0.97997902 0.99188312 1.         0.98800675 0.99600797 1.
 0.9960044  1.         0.97198896 0.98794894 0.97989788 0.9800072 ]


In [3]:
# Overlap
