In [11]:
import numpy as np
import matplotlib.pyplot as plt
import random
%matplotlib inline
N=14
xi_pattern=np.zeros(N)
for i in range(N):
    if random.uniform(0,1)<0.5:
        xi_pattern[i]=1
    else:
        xi_pattern[i]=-1
print(xi_pattern)

[-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1. -1. -1. -1.]


In [12]:
w=np.zeros((N,N))
for i in range(N):
    for j in range(N):
        w[i,j]=1/N*xi_pattern[i]*xi_pattern[j]
print(w)

[[ 0.07142857  0.07142857 -0.07142857 -0.07142857 -0.07142857 -0.07142857
  -0.07142857  0.07142857  0.07142857  0.07142857 -0.07142857  0.07142857
   0.07142857  0.07142857]
 [ 0.07142857  0.07142857 -0.07142857 -0.07142857 -0.07142857 -0.07142857
  -0.07142857  0.07142857  0.07142857  0.07142857 -0.07142857  0.07142857
   0.07142857  0.07142857]
 [-0.07142857 -0.07142857  0.07142857  0.07142857  0.07142857  0.07142857
   0.07142857 -0.07142857 -0.07142857 -0.07142857  0.07142857 -0.07142857
  -0.07142857 -0.07142857]
 [-0.07142857 -0.07142857  0.07142857  0.07142857  0.07142857  0.07142857
   0.07142857 -0.07142857 -0.07142857 -0.07142857  0.07142857 -0.07142857
  -0.07142857 -0.07142857]
 [-0.07142857 -0.07142857  0.07142857  0.07142857  0.07142857  0.07142857
   0.07142857 -0.07142857 -0.07142857 -0.07142857  0.07142857 -0.07142857
  -0.07142857 -0.07142857]
 [-0.07142857 -0.07142857  0.07142857  0.07142857  0.07142857  0.07142857
   0.07142857 -0.07142857 -0.07142857 -0.07142857  

In [16]:
xi0=np.zeros(N)
for i in range(N):
    if random.uniform(0,1)<0.2:
        xi0[i]=-xi_pattern[i]
    else:
        xi0[i]=xi_pattern[i]
print(xi0)
xi=np.zeros(N)
for i in range(N):
    sum=0
    for j in range(N):
        sum=sum+w[i,j]*xi0[j]
    if sum>0:
        xi[i]=1
    elif sum==0:
        xi[i]=0
    else:
        xi[i]=-1
print(xi_pattern)
print(xi)

[-1.  1.  1.  1.  1.  1.  1. -1. -1. -1.  1. -1. -1. -1.]
[-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1. -1. -1. -1.]
[-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1. -1. -1. -1.]
